version: "3.9"

volumes:
  postgres_data:
    name: postgres_data
    external: true
  thumbnails:
    name: thumbnails
    external: true

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "postgres"
    network_mode: host
    environment:
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DB=obj
      - WEB3_HTTP_PROVIDER_URL=${WEB3_HTTP_PROVIDER_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=obj
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    build:
      context: .
      dockerfile: postgis.Dockerfile

  thumbnailer:
    build:
      context: ./thumbnailer
    restart: always
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
